// Per-artist song database. Artists with an empty (or missing) array show a "coming soon" message.
const artistSongs = {
    "xxxtentacion": [
        { name: "#ImSippinTeaInYoHood", file: "audio/- Album - LOOK AT ME; THE ALBUM/#ImSippinTeaInYoHood (152kbit_Opus).opus" },
        { name: "$$$", file: "audio/- Album - ¿/$$$ (160kbit_Opus).opus" },
        { name: "100", file: "audio/- Album - 21XXX/100 (128kbit_AAC).m4a" },
        { name: "21 Guns", file: "audio/- Album - 21XXX/21 Guns (128kbit_AAC).m4a" },
        { name: "4Peat", file: "audio/XXXTENTACION Vol. 3/4Peat (128kbit_AAC).m4a" },
        { name: "777", file: "audio/XXXTENTACION Vol. 3/777 (128kbit_AAC).m4a" },
        { name: "ALONE, PART 3", file: "audio/- Album - LOOK AT ME; THE ALBUM/ALONE, PART 3 (152kbit_Opus).opus" },
        { name: "Amy Winehouse", file: "audio/- Album - 21XXX/Amy Winehouse (128kbit_AAC).m4a" },
        { name: "ATTENTION!", file: "audio/- Album - Bad Vibes Forever/ATTENTION! (152kbit_Opus).opus" },
        { name: "Ayala (Outro)", file: "audio/- Album - 17/Ayala (Outro) (152kbit_Opus).opus" },
        { name: "bad vibes forever (feat. PnB Rock & Trippie Redd)", file: "audio/- Album - Bad Vibes Forever/bad vibes forever (feat. PnB Rock & Trippie Redd) (128kbit_AAC).m4a" },
        { name: "BAD!", file: "audio/- Album - SKINS/BAD! (160kbit_Opus).opus" },
        { name: "before I close my eyes", file: "audio/- Album - LOOK AT ME; THE ALBUM/before I close my eyes (128kbit_AAC).m4a" },
        { name: "before i realize", file: "audio/- Album - Bad Vibes Forever/before i realize (128kbit_AAC).m4a" },
        { name: "Boost!", file: "audio/XXXTENTACION Vol. 3/Boost! (128kbit_AAC).m4a" },
        { name: "Bowser", file: "audio/XXXTENTACION Vol. 3/Bowser (128kbit_AAC).m4a" },
        { name: "BullS##t", file: "audio/- Album - 21XXX/BullS##t (128kbit_AAC).m4a" },
        { name: "Butthole Girl!", file: "audio/XXXTENTACION Vol. 3/Butthole Girl! (128kbit_AAC).m4a" },
        { name: "Came2Kill", file: "audio/XXXTENTACION Vol. 3/Came2Kill (128kbit_AAC).m4a" },
        { name: "Carry On", file: "audio/- Album - 17/Carry On (128kbit_AAC).m4a" },
        { name: "changes", file: "audio/- Album - LOOK AT ME; THE ALBUM/changes (152kbit_Opus).opus" },
        { name: "CHASE ⁄ glass shards (feat. ikabodVEINS)", file: "audio/- Album - Bad Vibes Forever/CHASE ⁄ glass shards (feat. ikabodVEINS) (128kbit_AAC).m4a" },
        { name: "Chokehold", file: "audio/XXXTENTACION Vol. 3/Chokehold (152kbit_Opus).opus" },
        { name: "Cold Weather", file: "audio/XXXTENTACION Vol. 4/Cold Weather (128kbit_AAC).m4a" },
        { name: "Corey's Intro", file: "audio/XXXTENTACION Vol. 4/Corey's Intro (128kbit_AAC).m4a" },
        { name: "Curse", file: "audio/XXXTENTACION Vol. 3/Curse (128kbit_AAC).m4a" },
        { name: "Daemons (feat. Joey Bada$$)", file: "audio/- Album - Bad Vibes Forever/Daemons (feat. Joey Bada$$) (128kbit_AAC).m4a" },
        { name: "Dead Inside (Interlude)", file: "audio/- Album - 17/Dead Inside (Interlude) (128kbit_AAC).m4a" },
        { name: "Depression & Obsession", file: "audio/- Album - 17/Depression & Obsession (128kbit_AAC).m4a" },
        { name: "difference (interlude)", file: "audio/- Album - SKINS/difference (interlude) (128kbit_AAC).m4a" },
        { name: "Eat It Up", file: "audio/- Album - Bad Vibes Forever/Eat It Up (152kbit_Opus).opus" },
        { name: "Ecstasy (feat. Noah Cyrus)", file: "audio/- Album - Bad Vibes Forever/Ecstasy (feat. Noah Cyrus) (128kbit_AAC).m4a" },
        { name: "Empty", file: "audio/XXXTENTACION Vol. 4/Empty (128kbit_AAC).m4a" },
        { name: "Everybody Dies In Their Nightmares", file: "audio/- Album - 17/Everybody Dies In Their Nightmares (128kbit_AAC).m4a" },
        { name: "Ex Bitch", file: "audio/- Album - Bad Vibes Forever/Ex Bitch (128kbit_AAC).m4a" },
        { name: "FAILURE IS NOT AN OPTION (Interlude)", file: "audio/- Album - LOOK AT ME; THE ALBUM/FAILURE IS NOT AN OPTION (Interlude) (128kbit_AAC).m4a" },
        { name: "Fall in Love with Death", file: "audio/XXXTENTACION Vol. 4/Fall in Love with Death (128kbit_AAC).m4a" },
        { name: "Floor 555", file: "audio/- Album - ¿/Floor 555 (128kbit_AAC).m4a" },
        { name: "Fuck Love", file: "audio/- Album - 17/Fuck Love (160kbit_Opus).opus" },
        { name: "Fuxk", file: "audio/- Album - 21XXX/Fuxk (128kbit_AAC).m4a" },
        { name: "FUXK", file: "audio/- Album - LOOK AT ME; THE ALBUM/FUXK (128kbit_AAC).m4a" },
        { name: "Gassed Up!", file: "audio/XXXTENTACION Vol. 4/Gassed Up! (152kbit_Opus).opus" },
        { name: "God Damn", file: "audio/XXXTENTACION Vol. 3/God Damn (128kbit_AAC).m4a" },
        { name: "going down!", file: "audio/- Album - ¿/going down! (128kbit_AAC).m4a" },
        { name: "Guardian angel", file: "audio/- Album - SKINS/Guardian angel (128kbit_AAC).m4a" },
        { name: "GXD", file: "audio/- Album - 21XXX/GXD (128kbit_AAC).m4a" },
        { name: "H2O", file: "audio/XXXTENTACION Vol. 3/H2O (128kbit_AAC).m4a" },
        { name: "He Diddy!", file: "audio/XXXTENTACION Vol. 4/He Diddy! (152kbit_Opus).opus" },
        { name: "HEARTEATER", file: "audio/- Album - Bad Vibes Forever/HEARTEATER (128kbit_AAC).m4a" },
        { name: "Hi Wendy!", file: "audio/XXXTENTACION Vol. 4/Hi Wendy! (128kbit_AAC).m4a" },
        { name: "hope", file: "audio/- Album - LOOK AT ME; THE ALBUM/hope (152kbit_Opus).opus" },
        { name: "Hope", file: "audio/- Album - ¿/Hope (152kbit_Opus).opus" },
        { name: "Hot Gyal (feat. Tory Lanez & Mavado)", file: "audio/- Album - Bad Vibes Forever/Hot Gyal (feat. Tory Lanez & Mavado) (152kbit_Opus).opus" },
        { name: "I Changed Her Life (feat. Rick Ross)", file: "audio/- Album - Bad Vibes Forever/I Changed Her Life (feat. Rick Ross) (128kbit_AAC).m4a" },
        { name: "I don’t even speak spanish lol", file: "audio/- Album - ¿/I don’t even speak spanish lol (152kbit_Opus).opus" },
        { name: "I don't let go", file: "audio/- Album - SKINS/I don't let go (152kbit_Opus).opus" },
        { name: "I Don't Wanna Do This Anymore", file: "audio/- Album - LOOK AT ME; THE ALBUM/I Don't Wanna Do This Anymore (128kbit_AAC).m4a" },
        { name: "I Might (feat. Youngboy)", file: "audio/- Album - 21XXX/I Might (feat. Youngboy) (128kbit_AAC).m4a" },
        { name: "I spoke to the devil in miami, he said everything would be fine", file: "audio/- Album - LOOK AT ME; THE ALBUM/I spoke to the devil in miami, he said everything would be fine (128kbit_AAC).m4a" },
        { name: "infinity (888)", file: "audio/- Album - ¿/infinity (888) (128kbit_AAC).m4a" },
        { name: "introduction", file: "audio/- Album - Bad Vibes Forever/introduction (128kbit_AAC).m4a" },
        { name: "Introduction", file: "audio/- Album - SKINS/Introduction (128kbit_AAC).m4a" },
        { name: "Introduction (instructions)", file: "audio/- Album - ¿/Introduction (instructions) (128kbit_AAC).m4a" },
        { name: "Invisible Klip", file: "audio/XXXTENTACION Vol. 3/Invisible Klip (128kbit_AAC).m4a" },
        { name: "IT'S ALL FADING TO BLACK (feat. blink-182)", file: "audio/- Album - Bad Vibes Forever/IT'S ALL FADING TO BLACK (feat. blink-182) (128kbit_AAC).m4a" },
        { name: "Jahseh on my Wrist", file: "audio/XXXTENTACION Vol. 4/Jahseh on my Wrist (128kbit_AAC).m4a" },
        { name: "Jocelyn Flores", file: "audio/- Album - 17/Jocelyn Flores (128kbit_AAC).m4a" },
        { name: "KILL ME (Pain From The Jail Phone)", file: "audio/- Album - LOOK AT ME; THE ALBUM/KILL ME (Pain From The Jail Phone) (128kbit_AAC).m4a" },
        { name: "Kill My Vibe (feat. Tom G)", file: "audio/- Album - Bad Vibes Forever/Kill My Vibe (feat. Tom G) (128kbit_AAC).m4a" },
        { name: "King Of The Dead", file: "audio/- Album - LOOK AT ME; THE ALBUM/King Of The Dead (128kbit_AAC).m4a" },
        { name: "King Zoo (feat. Fetty Wap)", file: "audio/- Album - 21XXX/King Zoo (feat. Fetty Wap) (128kbit_AAC).m4a" },
        { name: "LIMBO (feat. Killstation)", file: "audio/- Album - Bad Vibes Forever/LIMBO (feat. Killstation) (128kbit_AAC).m4a" },
        { name: "LOL", file: "audio/XXXTENTACION Vol. 3/LOL (128kbit_AAC).m4a" },
        { name: "Look At Me!", file: "audio/- Album - LOOK AT ME; THE ALBUM/Look At Me! (128kbit_AAC).m4a" },
        { name: "Love Hard, Fall Fast", file: "audio/XXXTENTACION Vol. 4/Love Hard, Fall Fast (128kbit_AAC).m4a" },
        { name: "love yourself (interlude)", file: "audio/- Album - ¿/love yourself (interlude) (128kbit_AAC).m4a" },
        { name: "Make Eem Run!", file: "audio/XXXTENTACION Vol. 4/Make Eem Run! (128kbit_AAC).m4a" },
        { name: "Maxipads for Everyone", file: "audio/XXXTENTACION Vol. 3/Maxipads for Everyone (128kbit_AAC).m4a" },
        { name: "Members Only Shit", file: "audio/XXXTENTACION Vol. 3/Members Only Shit (128kbit_AAC).m4a" },
        { name: "MEMBERS ONLY!", file: "audio/XXXTENTACION Vol. 4/MEMBERS ONLY! (128kbit_AAC).m4a" },
        { name: "Moonlight", file: "audio/- Album - LOOK AT ME; THE ALBUM/Moonlight (160kbit_Opus).opus" },
        { name: "Never", file: "audio/- Album - 21XXX/Never (128kbit_AAC).m4a" },
        { name: "NEVER", file: "audio/- Album - LOOK AT ME; THE ALBUM/NEVER (128kbit_AAC).m4a" },
        { name: "NorthStar (feat. Joyner Lucas)", file: "audio/- Album - Bad Vibes Forever/NorthStar (feat. Joyner Lucas) (160kbit_Opus).opus" },
        { name: "Nothing", file: "audio/XXXTENTACION Vol. 4/Nothing (152kbit_Opus).opus" },
        { name: "Now or Never", file: "audio/XXXTENTACION Vol. 4/Now or Never (128kbit_AAC).m4a" },
        { name: "NUMB", file: "audio/- Album - ¿/NUMB (128kbit_AAC).m4a" },
        { name: "numb the pain", file: "audio/- Album - Bad Vibes Forever/numb the pain (128kbit_AAC).m4a" },
        { name: "Off the Wall!", file: "audio/XXXTENTACION Vol. 3/Off the Wall! (128kbit_AAC).m4a" },
        { name: "Offended (feat. Meek Mill & Young Thug)", file: "audio/- Album - 21XXX/Offended (feat. Meek Mill & Young Thug) (128kbit_AAC).m4a" },
        { name: "On That Bitch", file: "audio/XXXTENTACION Vol. 3/On That Bitch (128kbit_AAC).m4a" },
        { name: "One Minute (feat. Kanye West & Travis Barker)", file: "audio/- Album - SKINS/One Minute (feat. Kanye West & Travis Barker) (128kbit_AAC).m4a" },
        { name: "Orlando", file: "audio/- Album - 17/Orlando (128kbit_AAC).m4a" },
        { name: "Over the Rainbow", file: "audio/XXXTENTACION Vol. 4/Over the Rainbow (128kbit_AAC).m4a" },
        { name: "Pain = BESTFRIEND", file: "audio/- Album - ¿/Pain = BESTFRIEND (152kbit_Opus).opus" },
        { name: "Pick Your Poison", file: "audio/XXXTENTACION Vol. 4/Pick Your Poison (128kbit_AAC).m4a" },
        { name: "Plottin", file: "audio/XXXTENTACION Vol. 4/Plottin (128kbit_AAC).m4a" },
        { name: "PROUD PUPPY LOVER!", file: "audio/XXXTENTACION Vol. 4/PROUD PUPPY LOVER! (128kbit_AAC).m4a" },
        { name: "Radar", file: "audio/XXXTENTACION Vol. 4/Radar (128kbit_AAC).m4a" },
        { name: "rare", file: "audio/- Album - LOOK AT ME; THE ALBUM/rare (128kbit_AAC).m4a" },
        { name: "Rebirth (2016)", file: "audio/XXXTENTACION Vol. 4/Rebirth (2016) (128kbit_AAC).m4a" },
        { name: "Red Pills (Love in the Matrix)", file: "audio/XXXTENTACION Vol. 4/Red Pills (Love in the Matrix) (128kbit_AAC).m4a" },
        { name: "Revenge", file: "audio/- Album - 17/Revenge (128kbit_AAC).m4a" },
        { name: "Royalty (feat. Ky-Mani Marley, Stefflon Don & Vybz Kartel)", file: "audio/- Album - Bad Vibes Forever/Royalty (feat. Ky-Mani Marley, Stefflon Don & Vybz Kartel) (128kbit_AAC).m4a" },
        { name: "SAD!", file: "audio/- Album - LOOK AT ME; THE ALBUM/SAD! (128kbit_AAC).m4a" },
        { name: "Sauce!", file: "audio/XXXTENTACION Vol. 4/Sauce! (128kbit_AAC).m4a" },
        { name: "Save Me", file: "audio/- Album - 17/Save Me (128kbit_AAC).m4a" },
        { name: "schizophrenia", file: "audio/- Album - ¿/schizophrenia (128kbit_AAC).m4a" },
        { name: "School Shooters (feat. Lil Wayne)", file: "audio/- Album - Bad Vibes Forever/School Shooters (feat. Lil Wayne) (128kbit_AAC).m4a" },
        { name: "Shoot (feat. Lil Durk)", file: "audio/- Album - 21XXX/Shoot (feat. Lil Durk) (128kbit_AAC).m4a" },
        { name: "Slipknot", file: "audio/XXXTENTACION Vol. 3/Slipknot (128kbit_AAC).m4a" },
        { name: "SMASH!", file: "audio/- Album - ¿/SMASH! (160kbit_Opus).opus" },
        { name: "STARING AT THE SKY", file: "audio/- Album - SKINS/STARING AT THE SKY (128kbit_AAC).m4a" },
        { name: "Static Shock", file: "audio/XXXTENTACION Vol. 3/Static Shock (128kbit_AAC).m4a" },
        { name: "Supra", file: "audio/XXXTENTACION Vol. 3/Supra (128kbit_AAC).m4a" },
        { name: "The Explanation", file: "audio/- Album - 17/The Explanation (128kbit_AAC).m4a" },
        { name: "the interlude that never ends", file: "audio/- Album - Bad Vibes Forever/the interlude that never ends (128kbit_AAC).m4a" },
        { name: "THE ONLY TIME I FEEL ALIVE", file: "audio/- Album - Bad Vibes Forever/THE ONLY TIME I FEEL ALIVE (128kbit_AAC).m4a" },
        { name: "the remedy for a broken heart (why am I so in love)", file: "audio/- Album - ¿/the remedy for a broken heart (why am I so in love) (128kbit_AAC).m4a" },
        { name: "Touch Eem Body", file: "audio/XXXTENTACION Vol. 4/Touch Eem Body (128kbit_AAC).m4a" },
        { name: "Train food", file: "audio/- Album - LOOK AT ME; THE ALBUM/Train food (128kbit_AAC).m4a" },
        { name: "Triumph", file: "audio/- Album - Bad Vibes Forever/Triumph (128kbit_AAC).m4a" },
        { name: "True Love", file: "audio/- Album - LOOK AT ME; THE ALBUM/True Love (128kbit_AAC).m4a" },
        { name: "UGLY", file: "audio/- Album - Bad Vibes Forever/UGLY (128kbit_AAC).m4a" },
        { name: "Valentine", file: "audio/- Album - 21XXX/Valentine (128kbit_AAC).m4a" },
        { name: "vice city", file: "audio/- Album - LOOK AT ME; THE ALBUM/vice city (128kbit_AAC).m4a" },
        { name: "Voss (feat. Sauce Walka & Carnage)", file: "audio/- Album - Bad Vibes Forever/Voss (feat. Sauce Walka & Carnage) (128kbit_AAC).m4a" },
        { name: "Vulture", file: "audio/XXXTENTACION Vol. 3/Vulture (152kbit_Opus).opus" },
        { name: "wanna grow old (i won't let go) (feat. Jimmy Levy)", file: "audio/- Album - Bad Vibes Forever/wanna grow old (i won't let go) (feat. Jimmy Levy) (128kbit_AAC).m4a" },
        { name: "Wassup Bro!", file: "audio/XXXTENTACION Vol. 3/Wassup Bro! (128kbit_AAC).m4a" },
        { name: "what are you so afraid of", file: "audio/- Album - SKINS/what are you so afraid of (152kbit_Opus).opus" },
        { name: "What in XXXTarnation", file: "audio/XXXTENTACION Vol. 3/What in XXXTarnation (128kbit_AAC).m4a" },
        { name: "whoa (mind in awe)", file: "audio/- Album - SKINS/whoa (mind in awe) (152kbit_Opus).opus" },
        { name: "Willy Wonka Was a Child Murderer", file: "audio/- Album - LOOK AT ME; THE ALBUM/Willy Wonka Was a Child Murderer (128kbit_AAC).m4a" },
        { name: "WingRiddenAngel", file: "audio/- Album - LOOK AT ME; THE ALBUM/WingRiddenAngel (128kbit_AAC).m4a" },
        { name: "Woah (Freestyle)", file: "audio/XXXTENTACION Vol. 4/Woah (Freestyle) (128kbit_AAC).m4a" },
        { name: "You Are Not M.O.", file: "audio/XXXTENTACION Vol. 4/You Are Not M.O. (128kbit_AAC).m4a" },
        { name: "YuNg BrAtZ", file: "audio/- Album - LOOK AT ME; THE ALBUM/YuNg BrAtZ (128kbit_AAC).m4a" }
    ],
    "drake": [],
    "joji": [],
    "the-weeknd": [],
    "j-cole": [],
    "kendrick-lamar": [],
    "lil-uzi-vert": [],
    "nle-choppa": [],
    "travis-scott": [],
    "21-savage": [],
    "ynw-melly": [],
    "juice-wrld": [],
    "king-von": []
};
